[build]
  command = "npm install && npm run build:client"
  publish = "dist/spa"

[functions]
  directory = "netlify/functions"

[dev]
  targetPort = 8081

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
